# Generated by Django 4.1.8 on 2024-05-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tgbot", "0003_alter_tggroups_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Автор"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="books_files", verbose_name="Файл книги"
                    ),
                ),
                (
                    "file_id",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="id файла книги",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "user_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_books",
                        to="tgbot.user",
                        verbose_name="Загрузивший",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
    ]
