# Generated by Django 4.1.8 on 2024-05-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tgbot", "0003_alter_tggroups_options"),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_type",
            field=models.CharField(
                choices=[("txt", "txt"), ("fb2", "fb2")],
                default="txt",
                max_length=10,
                verbose_name="Тип книги",
            ),
        ),
        migrations.CreateModel(
            name="UserBookProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress_txt",
                    models.FloatField(
                        default=0.0,
                        help_text="Для книг типа TXT",
                        verbose_name="Прогресс",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progresses",
                        to="books.book",
                        verbose_name="Книга",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readed_books",
                        to="tgbot.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
