# Generated by Django 4.1.8 on 2024-05-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_alter_userbookprogress_progress_txt"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbookprogress",
            name="total_pages_txt_book",
            field=models.IntegerField(
                default=1,
                help_text="Для книг типа TXT",
                verbose_name="Общее количество страниц",
            ),
        ),
        migrations.AlterField(
            model_name="userbookprogress",
            name="progress_txt",
            field=models.IntegerField(
                default=1, help_text="Для книг типа TXT", verbose_name="Прогресс"
            ),
        ),
    ]
