# Generated by Django 4.1.8 on 2024-05-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_book_encoding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookprogress",
            name="progress_txt",
            field=models.IntegerField(
                default=0, help_text="Для книг типа TXT", verbose_name="Прогресс"
            ),
        ),
    ]
