# Generated by Django 4.1.8 on 2024-05-14 13:41

from django.db import migrations, models
import django.db.models.deletion
import utils.get_url_model


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "param_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование параметра"
                    ),
                ),
                (
                    "param_val",
                    models.TextField(
                        blank=True, null=True, verbose_name="Значение параметра"
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметр бота",
                "verbose_name_plural": "Параметры бота",
                "ordering": ["param_name"],
            },
        ),
        migrations.CreateModel(
            name="NewUser",
            fields=[
                ("user_id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Телеграм логин",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Фамилия"
                    ),
                ),
                ("first_name", models.CharField(max_length=256, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "main_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_fotos",
                        verbose_name="Основное фото",
                    ),
                ),
                (
                    "main_photo_id",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="id основного фото",
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="О себе"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "language_code",
                    models.CharField(
                        blank=True,
                        help_text="Telegram client's lang",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "registered",
                    models.BooleanField(default=False, verbose_name="Зарегистрирован"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("RU", "RU"), ("EN", "EN")],
                        default="RU",
                        max_length=50,
                        verbose_name="Выбранный язык",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        default="",
                        max_length=50,
                        verbose_name="Завершенный шаг регистрации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новый пользователь",
                "verbose_name_plural": "Новые пользователи",
            },
            bases=(models.Model, utils.get_url_model.GetUrlModelMixin),
        ),
        migrations.CreateModel(
            name="tgGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Группа пользователей"
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(
                        null=True, verbose_name="ИД чата в Телеграм"
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Ссылка на группу",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание группыt"
                    ),
                ),
                (
                    "for_all_users",
                    models.BooleanField(
                        default=False, verbose_name="Для всех пользователей"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="events",
                        verbose_name="Фото/Видео",
                    ),
                ),
                (
                    "file_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="file_id"
                    ),
                ),
                (
                    "show_for_users",
                    models.BooleanField(
                        default=False, verbose_name="Показывать пользователям"
                    ),
                ),
                (
                    "send_new_users",
                    models.BooleanField(
                        default=False,
                        verbose_name="Отправлять сообщения о новых пользователях",
                    ),
                ),
                (
                    "send_advertisements",
                    models.BooleanField(
                        default=False,
                        verbose_name="Отправлять сообщения о рекламных сообщениях",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram чат организации",
                "verbose_name_plural": "Telegram чаты организации",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Телеграм логин",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Фамилия"
                    ),
                ),
                ("first_name", models.CharField(max_length=256, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "main_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_fotos",
                        verbose_name="Основное фото",
                    ),
                ),
                (
                    "main_photo_id",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="id основного фото",
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="О себе"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "language_code",
                    models.CharField(
                        blank=True,
                        help_text="Telegram client's lang",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "registered",
                    models.BooleanField(default=False, verbose_name="Зарегистрирован"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("RU", "RU"), ("EN", "EN")],
                        default="RU",
                        max_length=50,
                        verbose_name="Выбранный язык",
                    ),
                ),
                (
                    "is_blocked_bot",
                    models.BooleanField(default=False, verbose_name="Заблокирован"),
                ),
                (
                    "is_banned",
                    models.BooleanField(default=False, verbose_name="Забанен"),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="Администратор"),
                ),
                (
                    "is_moderator",
                    models.BooleanField(default=False, verbose_name="Модератор"),
                ),
                (
                    "sport",
                    models.TextField(blank=True, null=True, verbose_name="Спорт"),
                ),
                (
                    "hobby",
                    models.TextField(blank=True, null=True, verbose_name="Хобби"),
                ),
                (
                    "needs",
                    models.TextField(blank=True, null=True, verbose_name="Потребности"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменен"),
                ),
                (
                    "verified_by_admin",
                    models.BooleanField(
                        default=False, verbose_name="Проверен администратором"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
            bases=(models.Model, utils.get_url_model.GetUrlModelMixin),
        ),
        migrations.CreateModel(
            name="UsertgGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tgbot.tggroups",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tgbot.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа пользователя",
                "verbose_name_plural": "Группы пользователя",
                "ordering": ["user", "group"],
            },
        ),
        migrations.CreateModel(
            name="UserActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=128)),
                ("text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tgbot.user"
                    ),
                ),
            ],
        ),
    ]
