# Generated by Django 4.1.8 on 2024-05-14 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tgbot", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewUser",
        ),
    ]
