# Generated by Django 4.1.8 on 2024-05-14 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tgbot", "0002_delete_newuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tggroups",
            options={
                "ordering": ["name"],
                "verbose_name": "Telegram чат",
                "verbose_name_plural": "Telegram чаты",
            },
        ),
    ]
