class StatusCode:
    ADMIN = "admin"
    APPLICANT = "applicant"
    OWNER = "owner"
    MANAGER = "manager"
    SELLER = "seller"
    SUPERVISOR = "supervisor"
    ACCOUNTANT = "accountant"
    DIRECTOR = "director"
    ASSOCIATE_DIRECTOR = "associate_director"
    AGENT = "agent"

class MessageTemplatesCode:
    REG_REMINDER = "reg_reminder"
    HAPPY_BIRTHDAY = "happy_birthday"
    SEND_CONFIRM_EVENT = "send_confirm_event"
    WELCOME_NEWUSER_MESSAGE = "welcome_newuser_message"
    WAIT_APPOVE_MESSAGE = "wait_approve_message"
    PROFILE_APPROVED = "profile_approved_message"
    WELCOME_MESSAGE = "welcome_message"
    WELCOME_BLOCKERD_USR_MESSAGE = "welcome_blockerd_usr_message"
    WELCOME_BANNED_USR_MESSAGE = "welcome_banned_usr_message"